name: Bot runner

on:
  # 手動実行を許可
  workflow_dispatch:
  # 定刻に実行
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Setup dependencies
        run: uv sync --locked

      - name: Run Bluesky Bot
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_APP_PASSWORD: ${{ secrets.BSKY_APP_PASSWORD }}
          TANITA_CLIENT_ID: ${{ secrets.TANITA_CLIENT_ID }}
          TANITA_CLIENT_SECRET: ${{ secrets.TANITA_CLIENT_SECRET }}
          TANITA_REFRESH_TOKEN: ${{ secrets.TANITA_REFRESH_TOKEN }}
        run: |
          uv run ./.src/bot_bsky.py