name: Daily report

on:
  workflow_dispatch:
  schedule:
    # 15:45 JST = 6:45 UTC
    - cron: '45 6 * * 1-5'

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7

      - name: Sync dependencies
        run: uv sync

      - name: Run script for bot
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          KABU_PRICES_JSON_BASE64:  ${{ secrets.KABU_PRICES_JSON_BASE64 }}
        run: uv run ./.src/discord_kabu_daily_report.py

