name: Weekly Report

on:
  workflow_dispatch:
  schedule:
    # 毎週金曜日
    # 16:00 JST = 7:00 UTC
    - cron: '0 7 * * 5'

jobs:
  run-weekly-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv sync

      - name: Run weekly report
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          KABU_PRICES_JSON_BASE64:  ${{ secrets.KABU_PRICES_JSON_BASE64 }}
        run: |
          uv run ./.src/discord_kabu_weekly_report.py

