name: Haiku runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "latest"

      - name: Setup dependencies
        run: uv sync --locked

      - name: Generate Haiku
        env:
          SAKURA_API_KEY: ${{ secrets.SAKURA_API_KEY }}
        run: |
          uv run ./.src/haiku_generator.py

      - name: Commit and push haiku.log
        env:
          GIT_USER_NAME: "${{ secrets.GIT_USER_NAME }}"
          GIT_EMAIL: "${{ secrets.GIT_EMAIL }}"
        run: |
          git config user.name "${GIT_USER_NAME}"
          git config user.email "${GIT_EMAIL}"
          git add .data/haiku.log
          git commit -m "Update Haiku file by CI." || { echo "No changes to commit"; exit 0; }
          git push https://x-access-token:${{ secrets.TOKEN_FOR_WRITE }}@github.com/${{ github.actor }}/${{ github.actor }}.github.io.git main